[package]
name = "dcd2pdb"
version = "0.1.0"
edition = "2021"

[dependencies]
tryamp = { git = "https://github.com/Fritz1414213562/tryamp-rust.git" }
clap = { version = "3.1.8", features = ["derive"] }

